[package]
name = "trace-reader"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
streaming-types = { path = "../streaming-types" }

anyhow.workspace = true
clap.workspace = true
rdkafka.workspace = true
tokio.workspace = true


chrono = "0.4.22"
dotenv = "0.15.0"
env_logger = "0.10"
kagiyama = "0.3.0"
log = "0.4"
itertools = "0.11.0"
rand = "0.8.5"
