[package]
name = "supermusr-streaming-types"
version.workspace = true
license.workspace = true
edition.workspace = true

[build-dependencies]
flatc-rust = "*"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
flatbuffers.workspace = true
