[workspace]
resolver = "2"
members = [
  "common",
  "events-to-histogram",
  "simulator",
  "stream-to-file",
  "streaming-types",
  "trace-archiver",
  "trace-archiver-tdengine",
  "trace-to-events",
]

[workspace.package]
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
chrono = "0.4.31"
clap = { version = "4.4", features = ["derive", "env"] }
env_logger = "0.10"
hdf5 = "0.8.1"
kagiyama = "0.3.0"
lazy_static = "1.4.0"
log = "0.4"
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
rdkafka = { version = "0.34.0", features = ["cmake-build", "ssl-vendored", "gssapi-vendored", "sasl"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.33", features = ["macros", "rt-multi-thread"] }
