[package]
name = "trace-to-events"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
streaming-types = { path = "../streaming-types" }
trace-to-pulses = { path = "../trace-to-pulses" }

anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
itertools = "0.11.0"
kagiyama.workspace = true
lazy_static.workspace = true
log.workspace = true
rayon = "1.5.3"
rdkafka.workspace = true
tokio.workspace = true

[dev-dependencies]
chrono.workspace = true
