[package]
name = "trace-to-events"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
streaming-types = { path = "../streaming-types" }

anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
kagiyama.workspace = true
lazy_static.workspace = true
log.workspace = true
rdkafka.workspace = true
tokio.workspace = true

num = "0.4.1"
rayon = "1.8.0"

[dev-dependencies]
assert_approx_eq = "1.1.0"
chrono.workspace = true
rand = "0.8.5"
