---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Install TDEngineClient
        run: |
          nix develop --command sudo apt update
          nix develop --command sudo apt install wget tar
          nix develop --command TDENGINE_VERSION=3.0.4.2
          nix develop --command wget -c https://www.taosdata.com/assets-download/3.0/TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz
          nix develop --command tar xvf TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz
          nix develop --command cd TDengine-client-${TDENGINE_VERSION}
          nix develop --command ./install_client.sh
          nix develop --command cd ../
          nix develop --command rm -rf TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz TDengine-client-${TDENGINE_VERSION}

      - name: Build schema wrapper library
        run: pushd streaming-types && nix develop --command cargo build && popd

      - name: rustfmt
        run: nix develop --command cargo fmt -- --check

      - name: Clippy
        run: nix develop --command cargo clippy --all-targets --no-deps -- -Dwarnings

      - name: Build
        run: nix develop --command cargo build --all

      - name: Test
        run: nix develop --command cargo test --all
