---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20

      - name: Build schema wrapper library
        run: pushd streaming-types && nix develop --no-sandbox --command cargo build && popd

#      - name: Install TDEngineClient
#        run: |
#          nix develop --command sudo apt update; sudo apt install wget tar; TDENGINE_VERSION=3.0.4.2; wget -c https://www.taosdata.com/assets-download/3.0/TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz; tar xvf TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz; cd TDengine-client-${TDENGINE_VERSION}; ./install_client.sh; cd ../; rm -rf TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz TDengine-client-${TDENGINE_VERSION}

      - name: rustfmt
        run: nix develop --no-sandbox --command cargo fmt -- --check

      - name: Clippy
        run: nix develop --no-sandbox --command cargo clippy --all-targets --no-deps -- -Dwarnings

      - name: Build
        run: nix develop --no-sandbox --command cargo build --all

      - name: Test
        run: nix develop --no-sandbox --command cargo test --all
